### ISSUE TITLE
Gather Metadata from Plant Info Pages 

### ISSUE THREAD

**Issue by leonidscott** [UMM-CSci-3601-S17/digital-display-garden-iteration-2-omaranwar#5]

**Comment by CourtneyJC** [comment]
- [x] Get and store likes and dislikes
 - [x] Get and store comments
 - [x] Find a way to clear collections from databases (kinda. It works the way I want it to but there might be a better implementation)

**Comment by CourtneyJC** [comment]
So the issue I was having with the IDs was because in the PlantController, getPlant returned the string of json with only 2 fields: "commonName" and "cultivar", and the $oid was tacked onto the beginning. Changing that to return a third field, "id", fixed the issue right away.

Now everything should work with excel IDs and therefore the URLs wont change when you restart the database, though the comments, pageviews, and ratings will all be erased each time.
